<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>messageValidationRemoveItem</name>
   <tag></tag>
   <elementGuidId>59497b5e-22bf-495a-8458-481a42d04e46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;sc-item-C8d0d25e3-da77-4c34-b8d4-2fa1574cb4bc&quot;)/div[@class=&quot;sc-list-item-removed-msg&quot;]/div[@class=&quot;a-padding-medium&quot;][count(. | //div[@class = 'a-padding-medium' and @data-action = 'delete' and (text() = '   PlayStation 4 Slim 1TB Console  was removed from Shopping Cart.  ' or . = '   PlayStation 4 Slim 1TB Console  was removed from Shopping Cart.  ')]) = count(//div[@class = 'a-padding-medium' and @data-action = 'delete' and (text() = '   PlayStation 4 Slim 1TB Console  was removed from Shopping Cart.  ' or . = '   PlayStation 4 Slim 1TB Console  was removed from Shopping Cart.  ')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[4]/div/div[5]/div/div[2]/div[4]/form/div[2]/div/div[3]/div[1]/span/text()</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-padding-medium</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   PlayStation 4 Slim 1TB Console  was removed from Shopping Cart.  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-item-C8d0d25e3-da77-4c34-b8d4-2fa1574cb4bc&quot;)/div[@class=&quot;sc-list-item-removed-msg&quot;]/div[@class=&quot;a-padding-medium&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-item-C8d0d25e3-da77-4c34-b8d4-2fa1574cb4bc']/div[3]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Cart'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div[3]/div</value>
   </webElementXpaths>
</WebElementEntity>
